import Head from 'next/head'
import Navbar from '../../sdk/components/Navbar'
import ProductCard from '../../sdk/components/ProductCard'
import { IconButton } from '@mui/material'
import { useEffect, useMemo, useState } from 'react'

import styles from '../../styles/collection.module.scss'
import { useAuth } from '../../sdk/Hooks/useAuth'

const Collection = () => {
	const [totalProductCount, setTotalProductCount] = useState(12)
	const [productCount, setProductCount] = useState(12)
	const { authFetch, token } = useAuth()
	const [product, setProduct] = useState([])
	useEffect(() => {
		;(async () => {
			if (token !== null) {
				const productList = await authFetch(
					'/api/user/product?' +
						new URLSearchParams({
							category: 1,
							subCategory: 1,
							page: 1,
							limit: productCount,
						})
				)
				setProduct(productList.data.products)
				const totalProduct = await authFetch('/api/user/product/count')
				setTotalProductCount(totalProduct.data.count)
			}
		})()
	}, [authFetch, token, productCount])

	return (
		<>
			<Head>
				<title>Concepts Source Inc</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<div className={styles.collection}>
				<div className={styles.topBar}>
					<div>
						view |
						<IconButton
							onClick={() => {
								setProductCount(12)
							}}>
							12
						</IconButton>
						|
						<IconButton
							onClick={() => {
								setProductCount(24)
							}}>
							24
						</IconButton>
						|
						<IconButton
							onClick={() => {
								setProductCount(36)
							}}>
							36
						</IconButton>
					</div>
				</div>

				<div className={styles.productListGrid}>
					{product?.map((item, index) => {
						return <ProductCard key={item.id} product={item} />
					})}
				</div>
			</div>
		</>
	)
}

export default Collection
