import { Button, Grid } from '@mui/material'
import { Box } from '@mui/system'
import Head from 'next/head'
import Carousel from '../sdk/components/Carousel'
import Footer from '../sdk/components/Footer'
import Navbar from '../sdk/components/Navbar'
import styles from '../styles/home.module.scss'

export default function Home() {
	const cateogryList = [
		{
			name: 'apparel',
			imgUrl: '/assets/images/apparel.jpg',
			link: '#',
		},
		{
			name: 'accessories',
			imgUrl: '/assets/images/accessories.jpg',
			link: '#',
		},
		{
			name: 'handbag',
			imgUrl: '/assets/images/handbag.jpg',
			link: '#',
		},
		{
			name: 'home',
			imgUrl: '/assets/images/home.jpg',
			link: '#',
		},
		{
			name: 'jewellery',
			imgUrl: '/assets/images/jewellery.jpg',
			link: '#',
		},
		{
			name: 'view-all',
			imgUrl: '/assets/images/view-all.jpg',
			link: '#',
		},
	]
	return (
		<>
			<Head>
				<title>Concepts Source Inc</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<main>
				<div className={styles.carouselContainer}>
					<Carousel />
				</div>
				<div className={styles.categoryContainer}>
					<Grid container spacing={2}>
						{cateogryList.map((item, idx) => (
							<Grid key={idx} item xs={6} md={4}>
								<Button
									className={styles.cardBody}
									onClick={() => {
										console.log(item.link)
									}}>
									<img src={item.imgUrl} alt='name' />
									
								</Button>
							</Grid>
						))}
					</Grid>
				</div>
			</main>
			<Footer />
		</>
	)
}
