import { useRouter } from 'next/dist/client/router'
import Head from 'next/head'
import Carousel from '../sdk/components/Carousel'
import Footer from '../sdk/components/Footer'
import Navbar from '../sdk/components/Navbar'
import ProductCard from '../sdk/components/ProductCard'
import styles from '../styles/home.module.scss'

export default function Home() {
	const router = useRouter()
	const cateogryList = [
		{
			name: 'apparel',
			imgUrl: '/assets/images/apparel.jpg',
			link: '#',
		},
		{
			name: 'accessories',
			imgUrl: '/assets/images/accessories.jpg',
			link: '#',
		},
		{
			name: 'handbag',
			imgUrl: '/assets/images/handbag.jpg',
			link: '#',
		},
		{
			name: 'home',
			imgUrl: '/assets/images/home.jpg',
			link: '#',
		},
		{
			name: 'jewellery',
			imgUrl: '/assets/images/jewellery.jpg',
			link: '#',
		},
		{
			name: 'view-all',
			imgUrl: '/assets/images/view-all.jpg',
			link: '#',
		},
	]
	return (
		<>
			<Head>
				<title>Concepts Source Inc</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<main>
				<div className={styles.carouselContainer}>
					<Carousel />
				</div>

				<h1 className={styles.sectionHeading}>Collection</h1>
				<div className={styles.categoryContainer}>
					{cateogryList.map((item, index) => {
						return (
							<button
								key={index}
								className={styles.cardBody}
								onClick={() => {
									router.push('/collection/1')
								}}>
								<img src={item.imgUrl} alt={item.name} />
								<span>{item.name}</span>
							</button>
						)
					})}
				</div>

				<h1 className={styles.sectionHeading}>Popular Poroducts</h1>
				<div className={styles.popularProductContainer}>
					<ProductCard />
					<ProductCard />
					<ProductCard />
					<ProductCard />
					<ProductCard />
					<ProductCard />
				</div>
			</main>
			<Footer />
		</>
	)
}
